exclude: >
  (?x)^(
      v2/|
      aws-token-infra/|
      templates/ |
      .devcontainer/devcontainer.json
  )
fail_fast: true
minimum_pre_commit_version: '3.2.0'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    # -   id: no-commit-to-branch
    #     # GitHub only allows branch protection for teams or enterprise.
    #     args: ['--pattern', '^(?!T\d+.*)']
-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["--extend-ignore=E701"]
        additional_dependencies: [flake8-typing-imports==1.12.0]

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0  # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
        - id: terraform_fmt
        # - id: terraform_tfsec install is suboptimal

-   repo: local
    hooks:
    -   id: typescript-check
        name: Typescript Checker
        entry: npm run --prefix frontend_vue type-check
        types_or: [javascript, jsx, ts, tsx, vue]
        language: system
        pass_filenames: false
